/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: fileformat.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "fileformat.pb-c_gen.h"
void   blob__init
                     (Blob         *message)
{
  static Blob init_value = BLOB__INIT;
  *message = init_value;
}
size_t blob__get_packed_size
                     (const Blob *message)
{
  assert(message->base.descriptor == &blob__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blob__pack
                     (const Blob *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blob__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blob__pack_to_buffer
                     (const Blob *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blob__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blob *
       blob__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blob *)
     protobuf_c_message_unpack (&blob__descriptor,
                                allocator, len, data);
}
void   blob__free_unpacked
                     (Blob *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &blob__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   block_header__init
                     (BlockHeader         *message)
{
  static BlockHeader init_value = BLOCK_HEADER__INIT;
  *message = init_value;
}
size_t block_header__get_packed_size
                     (const BlockHeader *message)
{
  assert(message->base.descriptor == &block_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t block_header__pack
                     (const BlockHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &block_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t block_header__pack_to_buffer
                     (const BlockHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &block_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BlockHeader *
       block_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BlockHeader *)
     protobuf_c_message_unpack (&block_header__descriptor,
                                allocator, len, data);
}
void   block_header__free_unpacked
                     (BlockHeader *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &block_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor blob__field_descriptors[5] =
{
  {
    "raw",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Blob, has_raw),
    offsetof(Blob, raw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "raw_size",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Blob, has_raw_size),
    offsetof(Blob, raw_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zlib_data",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Blob, has_zlib_data),
    offsetof(Blob, zlib_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lzma_data",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Blob, has_lzma_data),
    offsetof(Blob, lzma_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bzip2_data",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Blob, has_bzip2_data),
    offsetof(Blob, bzip2_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blob__field_indices_by_name[] = {
  4,   /* field[4] = bzip2_data */
  3,   /* field[3] = lzma_data */
  0,   /* field[0] = raw */
  1,   /* field[1] = raw_size */
  2,   /* field[2] = zlib_data */
};
static const ProtobufCIntRange blob__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor blob__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Blob",
  "Blob",
  "Blob",
  "",
  sizeof(Blob),
  5,
  blob__field_descriptors,
  blob__field_indices_by_name,
  1,  blob__number_ranges,
  (ProtobufCMessageInit) blob__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor block_header__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BlockHeader, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indexdata",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(BlockHeader, has_indexdata),
    offsetof(BlockHeader, indexdata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "datasize",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BlockHeader, datasize),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned block_header__field_indices_by_name[] = {
  2,   /* field[2] = datasize */
  1,   /* field[1] = indexdata */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange block_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor block_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BlockHeader",
  "BlockHeader",
  "BlockHeader",
  "",
  sizeof(BlockHeader),
  3,
  block_header__field_descriptors,
  block_header__field_indices_by_name,
  1,  block_header__number_ranges,
  (ProtobufCMessageInit) block_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
