/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: osmformat.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "osmformat.pb-c_gen.h"
void   header_block__init
                     (HeaderBlock         *message)
{
  static HeaderBlock init_value = HEADER_BLOCK__INIT;
  *message = init_value;
}
size_t header_block__get_packed_size
                     (const HeaderBlock *message)
{
  assert(message->base.descriptor == &header_block__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t header_block__pack
                     (const HeaderBlock *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &header_block__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t header_block__pack_to_buffer
                     (const HeaderBlock *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &header_block__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HeaderBlock *
       header_block__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HeaderBlock *)
     protobuf_c_message_unpack (&header_block__descriptor,
                                allocator, len, data);
}
void   header_block__free_unpacked
                     (HeaderBlock *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &header_block__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   header_bbox__init
                     (HeaderBBox         *message)
{
  static HeaderBBox init_value = HEADER_BBOX__INIT;
  *message = init_value;
}
size_t header_bbox__get_packed_size
                     (const HeaderBBox *message)
{
  assert(message->base.descriptor == &header_bbox__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t header_bbox__pack
                     (const HeaderBBox *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &header_bbox__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t header_bbox__pack_to_buffer
                     (const HeaderBBox *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &header_bbox__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HeaderBBox *
       header_bbox__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HeaderBBox *)
     protobuf_c_message_unpack (&header_bbox__descriptor,
                                allocator, len, data);
}
void   header_bbox__free_unpacked
                     (HeaderBBox *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &header_bbox__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   primitive_block__init
                     (PrimitiveBlock         *message)
{
  static PrimitiveBlock init_value = PRIMITIVE_BLOCK__INIT;
  *message = init_value;
}
size_t primitive_block__get_packed_size
                     (const PrimitiveBlock *message)
{
  assert(message->base.descriptor == &primitive_block__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t primitive_block__pack
                     (const PrimitiveBlock *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &primitive_block__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t primitive_block__pack_to_buffer
                     (const PrimitiveBlock *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &primitive_block__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PrimitiveBlock *
       primitive_block__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PrimitiveBlock *)
     protobuf_c_message_unpack (&primitive_block__descriptor,
                                allocator, len, data);
}
void   primitive_block__free_unpacked
                     (PrimitiveBlock *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &primitive_block__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   primitive_group__init
                     (PrimitiveGroup         *message)
{
  static PrimitiveGroup init_value = PRIMITIVE_GROUP__INIT;
  *message = init_value;
}
size_t primitive_group__get_packed_size
                     (const PrimitiveGroup *message)
{
  assert(message->base.descriptor == &primitive_group__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t primitive_group__pack
                     (const PrimitiveGroup *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &primitive_group__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t primitive_group__pack_to_buffer
                     (const PrimitiveGroup *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &primitive_group__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PrimitiveGroup *
       primitive_group__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PrimitiveGroup *)
     protobuf_c_message_unpack (&primitive_group__descriptor,
                                allocator, len, data);
}
void   primitive_group__free_unpacked
                     (PrimitiveGroup *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &primitive_group__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   string_table__init
                     (StringTable         *message)
{
  static StringTable init_value = STRING_TABLE__INIT;
  *message = init_value;
}
size_t string_table__get_packed_size
                     (const StringTable *message)
{
  assert(message->base.descriptor == &string_table__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t string_table__pack
                     (const StringTable *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &string_table__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t string_table__pack_to_buffer
                     (const StringTable *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &string_table__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StringTable *
       string_table__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StringTable *)
     protobuf_c_message_unpack (&string_table__descriptor,
                                allocator, len, data);
}
void   string_table__free_unpacked
                     (StringTable *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &string_table__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   info__init
                     (Info         *message)
{
  static Info init_value = INFO__INIT;
  *message = init_value;
}
size_t info__get_packed_size
                     (const Info *message)
{
  assert(message->base.descriptor == &info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t info__pack
                     (const Info *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t info__pack_to_buffer
                     (const Info *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Info *
       info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Info *)
     protobuf_c_message_unpack (&info__descriptor,
                                allocator, len, data);
}
void   info__free_unpacked
                     (Info *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dense_info__init
                     (DenseInfo         *message)
{
  static DenseInfo init_value = DENSE_INFO__INIT;
  *message = init_value;
}
size_t dense_info__get_packed_size
                     (const DenseInfo *message)
{
  assert(message->base.descriptor == &dense_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dense_info__pack
                     (const DenseInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dense_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dense_info__pack_to_buffer
                     (const DenseInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dense_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DenseInfo *
       dense_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DenseInfo *)
     protobuf_c_message_unpack (&dense_info__descriptor,
                                allocator, len, data);
}
void   dense_info__free_unpacked
                     (DenseInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &dense_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   change_set__init
                     (ChangeSet         *message)
{
  static ChangeSet init_value = CHANGE_SET__INIT;
  *message = init_value;
}
size_t change_set__get_packed_size
                     (const ChangeSet *message)
{
  assert(message->base.descriptor == &change_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t change_set__pack
                     (const ChangeSet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &change_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t change_set__pack_to_buffer
                     (const ChangeSet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &change_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChangeSet *
       change_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChangeSet *)
     protobuf_c_message_unpack (&change_set__descriptor,
                                allocator, len, data);
}
void   change_set__free_unpacked
                     (ChangeSet *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &change_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   node__init
                     (Node         *message)
{
  static Node init_value = NODE__INIT;
  *message = init_value;
}
size_t node__get_packed_size
                     (const Node *message)
{
  assert(message->base.descriptor == &node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t node__pack
                     (const Node *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t node__pack_to_buffer
                     (const Node *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Node *
       node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Node *)
     protobuf_c_message_unpack (&node__descriptor,
                                allocator, len, data);
}
void   node__free_unpacked
                     (Node *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dense_nodes__init
                     (DenseNodes         *message)
{
  static DenseNodes init_value = DENSE_NODES__INIT;
  *message = init_value;
}
size_t dense_nodes__get_packed_size
                     (const DenseNodes *message)
{
  assert(message->base.descriptor == &dense_nodes__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dense_nodes__pack
                     (const DenseNodes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dense_nodes__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dense_nodes__pack_to_buffer
                     (const DenseNodes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dense_nodes__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DenseNodes *
       dense_nodes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DenseNodes *)
     protobuf_c_message_unpack (&dense_nodes__descriptor,
                                allocator, len, data);
}
void   dense_nodes__free_unpacked
                     (DenseNodes *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &dense_nodes__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   way__init
                     (Way         *message)
{
  static Way init_value = WAY__INIT;
  *message = init_value;
}
size_t way__get_packed_size
                     (const Way *message)
{
  assert(message->base.descriptor == &way__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t way__pack
                     (const Way *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &way__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t way__pack_to_buffer
                     (const Way *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &way__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Way *
       way__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Way *)
     protobuf_c_message_unpack (&way__descriptor,
                                allocator, len, data);
}
void   way__free_unpacked
                     (Way *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &way__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   relation__init
                     (Relation         *message)
{
  static Relation init_value = RELATION__INIT;
  *message = init_value;
}
size_t relation__get_packed_size
                     (const Relation *message)
{
  assert(message->base.descriptor == &relation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t relation__pack
                     (const Relation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &relation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t relation__pack_to_buffer
                     (const Relation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &relation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Relation *
       relation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Relation *)
     protobuf_c_message_unpack (&relation__descriptor,
                                allocator, len, data);
}
void   relation__free_unpacked
                     (Relation *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &relation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor header_block__field_descriptors[5] =
{
  {
    "bbox",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(HeaderBlock, bbox),
    &header_bbox__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "required_features",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(HeaderBlock, n_required_features),
    offsetof(HeaderBlock, required_features),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "optional_features",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(HeaderBlock, n_optional_features),
    offsetof(HeaderBlock, optional_features),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "writingprogram",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HeaderBlock, writingprogram),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HeaderBlock, source),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned header_block__field_indices_by_name[] = {
  0,   /* field[0] = bbox */
  2,   /* field[2] = optional_features */
  1,   /* field[1] = required_features */
  4,   /* field[4] = source */
  3,   /* field[3] = writingprogram */
};
static const ProtobufCIntRange header_block__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 4, 1 },
  { 16, 3 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor header_block__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "HeaderBlock",
  "HeaderBlock",
  "HeaderBlock",
  "",
  sizeof(HeaderBlock),
  5,
  header_block__field_descriptors,
  header_block__field_indices_by_name,
  3,  header_block__number_ranges,
  (ProtobufCMessageInit) header_block__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor header_bbox__field_descriptors[4] =
{
  {
    "left",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT64,
    0,   /* quantifier_offset */
    offsetof(HeaderBBox, left),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "right",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT64,
    0,   /* quantifier_offset */
    offsetof(HeaderBBox, right),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "top",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT64,
    0,   /* quantifier_offset */
    offsetof(HeaderBBox, top),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bottom",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT64,
    0,   /* quantifier_offset */
    offsetof(HeaderBBox, bottom),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned header_bbox__field_indices_by_name[] = {
  3,   /* field[3] = bottom */
  0,   /* field[0] = left */
  1,   /* field[1] = right */
  2,   /* field[2] = top */
};
static const ProtobufCIntRange header_bbox__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor header_bbox__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "HeaderBBox",
  "HeaderBBox",
  "HeaderBBox",
  "",
  sizeof(HeaderBBox),
  4,
  header_bbox__field_descriptors,
  header_bbox__field_indices_by_name,
  1,  header_bbox__number_ranges,
  (ProtobufCMessageInit) header_bbox__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const int32_t primitive_block__granularity__default_value = 100;
static const int64_t primitive_block__lat_offset__default_value = 0ll;
static const int64_t primitive_block__lon_offset__default_value = 0ll;
static const int32_t primitive_block__date_granularity__default_value = 1000;
static const ProtobufCFieldDescriptor primitive_block__field_descriptors[6] =
{
  {
    "stringtable",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PrimitiveBlock, stringtable),
    &string_table__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "primitivegroup",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PrimitiveBlock, n_primitivegroup),
    offsetof(PrimitiveBlock, primitivegroup),
    &primitive_group__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "granularity",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(PrimitiveBlock, has_granularity),
    offsetof(PrimitiveBlock, granularity),
    NULL,
    &primitive_block__granularity__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "date_granularity",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(PrimitiveBlock, has_date_granularity),
    offsetof(PrimitiveBlock, date_granularity),
    NULL,
    &primitive_block__date_granularity__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat_offset",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(PrimitiveBlock, has_lat_offset),
    offsetof(PrimitiveBlock, lat_offset),
    NULL,
    &primitive_block__lat_offset__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lon_offset",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(PrimitiveBlock, has_lon_offset),
    offsetof(PrimitiveBlock, lon_offset),
    NULL,
    &primitive_block__lon_offset__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned primitive_block__field_indices_by_name[] = {
  3,   /* field[3] = date_granularity */
  2,   /* field[2] = granularity */
  4,   /* field[4] = lat_offset */
  5,   /* field[5] = lon_offset */
  1,   /* field[1] = primitivegroup */
  0,   /* field[0] = stringtable */
};
static const ProtobufCIntRange primitive_block__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 17, 2 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor primitive_block__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PrimitiveBlock",
  "PrimitiveBlock",
  "PrimitiveBlock",
  "",
  sizeof(PrimitiveBlock),
  6,
  primitive_block__field_descriptors,
  primitive_block__field_indices_by_name,
  2,  primitive_block__number_ranges,
  (ProtobufCMessageInit) primitive_block__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor primitive_group__field_descriptors[5] =
{
  {
    "nodes",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PrimitiveGroup, n_nodes),
    offsetof(PrimitiveGroup, nodes),
    &node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dense",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PrimitiveGroup, dense),
    &dense_nodes__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ways",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PrimitiveGroup, n_ways),
    offsetof(PrimitiveGroup, ways),
    &way__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "relations",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PrimitiveGroup, n_relations),
    offsetof(PrimitiveGroup, relations),
    &relation__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "changesets",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PrimitiveGroup, n_changesets),
    offsetof(PrimitiveGroup, changesets),
    &change_set__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned primitive_group__field_indices_by_name[] = {
  4,   /* field[4] = changesets */
  1,   /* field[1] = dense */
  0,   /* field[0] = nodes */
  3,   /* field[3] = relations */
  2,   /* field[2] = ways */
};
static const ProtobufCIntRange primitive_group__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor primitive_group__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PrimitiveGroup",
  "PrimitiveGroup",
  "PrimitiveGroup",
  "",
  sizeof(PrimitiveGroup),
  5,
  primitive_group__field_descriptors,
  primitive_group__field_indices_by_name,
  1,  primitive_group__number_ranges,
  (ProtobufCMessageInit) primitive_group__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor string_table__field_descriptors[1] =
{
  {
    "s",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(StringTable, n_s),
    offsetof(StringTable, s),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned string_table__field_indices_by_name[] = {
  0,   /* field[0] = s */
};
static const ProtobufCIntRange string_table__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor string_table__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StringTable",
  "StringTable",
  "StringTable",
  "",
  sizeof(StringTable),
  1,
  string_table__field_descriptors,
  string_table__field_indices_by_name,
  1,  string_table__number_ranges,
  (ProtobufCMessageInit) string_table__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const int32_t info__version__default_value = -1;
static const ProtobufCFieldDescriptor info__field_descriptors[5] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Info, has_version),
    offsetof(Info, version),
    NULL,
    &info__version__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Info, has_timestamp),
    offsetof(Info, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "changeset",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Info, has_changeset),
    offsetof(Info, changeset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uid",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Info, has_uid),
    offsetof(Info, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_sid",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Info, has_user_sid),
    offsetof(Info, user_sid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned info__field_indices_by_name[] = {
  2,   /* field[2] = changeset */
  1,   /* field[1] = timestamp */
  3,   /* field[3] = uid */
  4,   /* field[4] = user_sid */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Info",
  "Info",
  "Info",
  "",
  sizeof(Info),
  5,
  info__field_descriptors,
  info__field_indices_by_name,
  1,  info__number_ranges,
  (ProtobufCMessageInit) info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dense_info__field_descriptors[5] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DenseInfo, n_version),
    offsetof(DenseInfo, version),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(DenseInfo, n_timestamp),
    offsetof(DenseInfo, timestamp),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "changeset",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(DenseInfo, n_changeset),
    offsetof(DenseInfo, changeset),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uid",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(DenseInfo, n_uid),
    offsetof(DenseInfo, uid),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_sid",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(DenseInfo, n_user_sid),
    offsetof(DenseInfo, user_sid),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dense_info__field_indices_by_name[] = {
  2,   /* field[2] = changeset */
  1,   /* field[1] = timestamp */
  3,   /* field[3] = uid */
  4,   /* field[4] = user_sid */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange dense_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor dense_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DenseInfo",
  "DenseInfo",
  "DenseInfo",
  "",
  sizeof(DenseInfo),
  5,
  dense_info__field_descriptors,
  dense_info__field_indices_by_name,
  1,  dense_info__number_ranges,
  (ProtobufCMessageInit) dense_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor change_set__field_descriptors[8] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(ChangeSet, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keys",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ChangeSet, n_keys),
    offsetof(ChangeSet, keys),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vals",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ChangeSet, n_vals),
    offsetof(ChangeSet, vals),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "info",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ChangeSet, info),
    &info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "created_at",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(ChangeSet, created_at),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "closetime_delta",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ChangeSet, has_closetime_delta),
    offsetof(ChangeSet, closetime_delta),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "open",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ChangeSet, open),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bbox",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ChangeSet, bbox),
    &header_bbox__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned change_set__field_indices_by_name[] = {
  7,   /* field[7] = bbox */
  5,   /* field[5] = closetime_delta */
  4,   /* field[4] = created_at */
  0,   /* field[0] = id */
  3,   /* field[3] = info */
  1,   /* field[1] = keys */
  6,   /* field[6] = open */
  2,   /* field[2] = vals */
};
static const ProtobufCIntRange change_set__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 8, 4 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor change_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ChangeSet",
  "ChangeSet",
  "ChangeSet",
  "",
  sizeof(ChangeSet),
  8,
  change_set__field_descriptors,
  change_set__field_indices_by_name,
  2,  change_set__number_ranges,
  (ProtobufCMessageInit) change_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor node__field_descriptors[6] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT64,
    0,   /* quantifier_offset */
    offsetof(Node, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keys",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Node, n_keys),
    offsetof(Node, keys),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vals",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Node, n_vals),
    offsetof(Node, vals),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "info",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Node, info),
    &info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT64,
    0,   /* quantifier_offset */
    offsetof(Node, lat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lon",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT64,
    0,   /* quantifier_offset */
    offsetof(Node, lon),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned node__field_indices_by_name[] = {
  0,   /* field[0] = id */
  3,   /* field[3] = info */
  1,   /* field[1] = keys */
  4,   /* field[4] = lat */
  5,   /* field[5] = lon */
  2,   /* field[2] = vals */
};
static const ProtobufCIntRange node__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 8, 4 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor node__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Node",
  "Node",
  "Node",
  "",
  sizeof(Node),
  6,
  node__field_descriptors,
  node__field_indices_by_name,
  2,  node__number_ranges,
  (ProtobufCMessageInit) node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dense_nodes__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(DenseNodes, n_id),
    offsetof(DenseNodes, id),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "denseinfo",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DenseNodes, denseinfo),
    &dense_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(DenseNodes, n_lat),
    offsetof(DenseNodes, lat),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lon",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(DenseNodes, n_lon),
    offsetof(DenseNodes, lon),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keys_vals",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DenseNodes, n_keys_vals),
    offsetof(DenseNodes, keys_vals),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dense_nodes__field_indices_by_name[] = {
  1,   /* field[1] = denseinfo */
  0,   /* field[0] = id */
  4,   /* field[4] = keys_vals */
  2,   /* field[2] = lat */
  3,   /* field[3] = lon */
};
static const ProtobufCIntRange dense_nodes__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 5, 1 },
  { 8, 2 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor dense_nodes__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DenseNodes",
  "DenseNodes",
  "DenseNodes",
  "",
  sizeof(DenseNodes),
  5,
  dense_nodes__field_descriptors,
  dense_nodes__field_indices_by_name,
  3,  dense_nodes__number_ranges,
  (ProtobufCMessageInit) dense_nodes__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor way__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Way, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keys",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Way, n_keys),
    offsetof(Way, keys),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vals",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Way, n_vals),
    offsetof(Way, vals),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "info",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Way, info),
    &info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "refs",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(Way, n_refs),
    offsetof(Way, refs),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned way__field_indices_by_name[] = {
  0,   /* field[0] = id */
  3,   /* field[3] = info */
  1,   /* field[1] = keys */
  4,   /* field[4] = refs */
  2,   /* field[2] = vals */
};
static const ProtobufCIntRange way__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 8, 4 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor way__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Way",
  "Way",
  "Way",
  "",
  sizeof(Way),
  5,
  way__field_descriptors,
  way__field_indices_by_name,
  2,  way__number_ranges,
  (ProtobufCMessageInit) way__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue relation__member_type__enum_values_by_number[3] =
{
  { "NODE", "RELATION__MEMBER_TYPE__NODE", 0 },
  { "WAY", "RELATION__MEMBER_TYPE__WAY", 1 },
  { "RELATION", "RELATION__MEMBER_TYPE__RELATION", 2 },
};
static const ProtobufCIntRange relation__member_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex relation__member_type__enum_values_by_name[3] =
{
  { "NODE", 0 },
  { "RELATION", 2 },
  { "WAY", 1 },
};
const ProtobufCEnumDescriptor relation__member_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Relation.MemberType",
  "MemberType",
  "Relation__MemberType",
  "",
  3,
  relation__member_type__enum_values_by_number,
  3,
  relation__member_type__enum_values_by_name,
  1,
  relation__member_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor relation__field_descriptors[7] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Relation, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keys",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Relation, n_keys),
    offsetof(Relation, keys),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vals",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Relation, n_vals),
    offsetof(Relation, vals),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "info",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Relation, info),
    &info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "roles_sid",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Relation, n_roles_sid),
    offsetof(Relation, roles_sid),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memids",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(Relation, n_memids),
    offsetof(Relation, memids),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "types",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Relation, n_types),
    offsetof(Relation, types),
    &relation__member_type__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned relation__field_indices_by_name[] = {
  0,   /* field[0] = id */
  3,   /* field[3] = info */
  1,   /* field[1] = keys */
  5,   /* field[5] = memids */
  4,   /* field[4] = roles_sid */
  6,   /* field[6] = types */
  2,   /* field[2] = vals */
};
static const ProtobufCIntRange relation__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 8, 4 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor relation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Relation",
  "Relation",
  "Relation",
  "",
  sizeof(Relation),
  7,
  relation__field_descriptors,
  relation__field_indices_by_name,
  2,  relation__number_ranges,
  (ProtobufCMessageInit) relation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
